"""Provides the frame acquisition timestamp extraction algorithm that reads VideoSystem log archives."""

from __future__ import annotations

from enum import StrEnum
from typing import TYPE_CHECKING
from contextlib import ExitStack
from multiprocessing import get_context
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
from ataraxis_base_utilities import console, resolve_worker_count
from ataraxis_data_structures import (
    PARALLEL_PROCESSING_THRESHOLD,
    LogArchiveReader,
    limit_worker_threads,
    initialize_worker_threads,
)

if TYPE_CHECKING:
    from pathlib import Path
    from multiprocessing.context import SpawnContext

    from numpy.typing import NDArray

_WORKER_THREAD_CEILING: int = 1
"""The number of threads each worker of a self-owned pool pins its numeric backends to."""

_MULTIPROCESSING_CONTEXT: SpawnContext = get_context("spawn")
"""The spawn-based multiprocessing context used to create the process pool that extracts frame timestamps, ensuring
identical cross-platform behavior on all supported platforms."""


class ExtractedDataColumns(StrEnum):
    """Defines the columns the extracted camera timestamp table carries, in the order it stores them."""

    FRAME_TIME = "frame_time_us"
    """The frame acquisition timestamps, in microseconds elapsed since the UTC epoch onset."""


def extract_logged_camera_timestamps(
    log_path: Path,
    workers: int = -1,
    *,
    display_progress: bool = True,
    executor: ProcessPoolExecutor | None = None,
) -> NDArray[np.uint64]:
    """Extracts the video camera frame acquisition timestamps from the target .npz log file.

    Reads the '.npz' archive that the assemble_log_archives() function of ataraxis-data-structures builds from a
    VideoSystem instance's DataLogger output and, if the system saved any frames acquired by the managed camera,
    extracts the array of frame timestamps. The order of timestamps in the array is sequential and matches the order
    in which the frames were appended to the .mp4 video file.

    Notes:
        The timestamps are given as microseconds elapsed since the UTC epoch onset.

        If the target .npz archive contains fewer than 2000 messages, the processing is carried out sequentially
        regardless of the specified worker-count.

        Returns a contiguous numpy array instead of a Python tuple to minimize memory footprint. For a 120 fps camera
        recording over 1.5 hours (~648,000 frames), this reduces timestamp storage from ~25 MB (Python objects) to
        ~5 MB (contiguous uint64 buffer).

        When an external executor is provided, batch processing is submitted to that executor instead of creating a
        new ProcessPoolExecutor. The caller is responsible for executor lifecycle management. This allows multiple
        archives with similar sizes to share a single process pool, avoiding the overhead of repeatedly spawning and
        tearing down worker processes.

    Args:
        log_path: The path to the .npz log file that stores the logged data generated by the VideoSystem
            instance during runtime.
        workers: The number of parallel worker processes (CPU cores) to use for processing. Setting this to a value
            below 1 auto-resolves the count to every available CPU core minus the cores reserved for the host system.
            Setting this to a value of 1 conducts the processing sequentially.
        display_progress: Determines whether to display a progress bar during parallel batch processing.
        executor: When provided, parallel batch work is submitted to this pool instead of a newly created one, and
            the caller owns the pool's lifecycle. Its worker count must match the workers value used for batch
            generation, and the caller is responsible for the worker thread limit its processes inherit.

    Returns:
        A contiguous numpy array of frame acquisition timestamps. Each timestamp is stored as the number of
        microseconds elapsed since the UTC epoch onset.

    Raises:
        ValueError: If the target path does not exist, does not have a .npz suffix, or does not point to a file.
    """
    # Validates the archive path. LogArchiveReader checks existence, but not the .npz suffix or file type.
    if not log_path.exists() or log_path.suffix != ".npz" or not log_path.is_file():
        message = (
            f"Unable to extract camera frame timestamp data from the log file {log_path}, as it does not exist or does "
            f"not point to a valid .npz archive."
        )
        console.error(message=message, error=ValueError)

    # Creates a reader for the target archive. The reader handles onset timestamp discovery and message key management.
    reader = LogArchiveReader(archive_path=log_path)

    # Processes sequentially for small archives or explicit single-worker requests to avoid multiprocessing overhead.
    # An archive holding no data messages also lands here and yields an empty array.
    if workers == 1 or reader.message_count < PARALLEL_PROCESSING_THRESHOLD:
        return np.fromiter(
            (message.timestamp_us for message in reader.iter_messages() if message.payload.size == 0),
            dtype=np.uint64,
        )

    # Resolves the number of workers if not already resolved by the caller. External executors are pre-sized, so
    # the caller provides a positive workers value that matches the executor's pool size.
    if workers < 1:
        workers = resolve_worker_count(requested_workers=workers)

    # Generates batches optimized for parallel processing. The batch_multiplier of 4 creates (workers * 4) batches
    # for over-batching, which improves load distribution when processing times vary.
    batches = reader.get_batches(workers=workers, batch_multiplier=4)

    # Passes the pre-discovered onset timestamp to worker processes so each can construct a lightweight reader that
    # skips redundant onset scanning.
    onset_us = reader.onset_timestamp_us

    # Uses the provided executor or creates a managed one for this invocation. Managed executors are shut down after
    # use, while external executors are left open for reuse across multiple archives. A managed pool pins its workers
    # from both sides: the environment limit reaches the backends that size their pool while importing, and the
    # initializer reaches the backends that read their width the first time they are asked to do work.
    with ExitStack() as pool_scope:
        if executor is not None:
            active_executor = executor
        else:
            pool_scope.enter_context(limit_worker_threads(thread_count=_WORKER_THREAD_CEILING))
            active_executor = ProcessPoolExecutor(
                max_workers=workers,
                mp_context=_MULTIPROCESSING_CONTEXT,
                initializer=initialize_worker_threads,
                initargs=(_WORKER_THREAD_CEILING,),
            )
            pool_scope.callback(active_executor.shutdown, wait=True)

        future_to_index = {
            active_executor.submit(
                _process_frame_message_batch, log_path=log_path, keys=batch_keys, onset_us=onset_us
            ): index
            for index, batch_keys in enumerate(batches)
        }

        # Collects results while maintaining frame order.
        results: list[NDArray[np.uint64] | None] = [None] * len(batches)

        if display_progress:
            with console.progress(
                total=len(batches), description="Extracting camera frame timestamps", unit="batch"
            ) as pbar:
                for future in as_completed(future_to_index):
                    results[future_to_index[future]] = future.result()
                    pbar.update(1)
        else:
            for future in as_completed(future_to_index):
                results[future_to_index[future]] = future.result()

    # Concatenates batch arrays into a single contiguous array. Filters out the empty arrays returned by batches
    # that held no frame messages, alongside the placeholders of any batch that never resolved.
    batch_arrays = [batch for batch in results if batch is not None and batch.size > 0]
    if not batch_arrays:
        return np.array([], dtype=np.uint64)

    return np.concatenate(batch_arrays)


def _process_frame_message_batch(log_path: Path, keys: list[str], onset_us: np.uint64) -> NDArray[np.uint64]:
    """Processes a batch of messages from a VideoSystem log archive to extract frame timestamps.

    Runs in parallel via ProcessPoolExecutor. Each worker creates its own LogArchiveReader instance with the
    pre-discovered onset timestamp to avoid redundant archive scanning. Returns a contiguous numpy array to minimize
    IPC serialization overhead and avoid Python object-per-timestamp memory cost.

    Args:
        log_path: The path to the .npz log archive file.
        keys: The message keys to process in this batch.
        onset_us: The pre-discovered onset timestamp in microseconds since epoch.

    Returns:
        A contiguous numpy array of absolute frame acquisition timestamps in microseconds since UTC epoch.
    """
    reader = LogArchiveReader(archive_path=log_path, onset_us=onset_us)
    return np.fromiter(
        (message.timestamp_us for message in reader.iter_messages(keys=keys) if message.payload.size == 0),
        dtype=np.uint64,
    )
