import numpy as np
from _typeshed import Incomplete

class Camera:
    num_connected: int
    video_capture: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    @property
    def is_connected(self) -> bool: ...
    def grab_frame(self) -> np.ndarray: ...
