from _typeshed import Incomplete

parser: Incomplete
logger: Incomplete

def get_video_size(filename): ...
def start_ffmpeg_process1(in_filename): ...
def start_ffmpeg_process2(out_filename, width, height): ...
def read_frame(process1, width, height): ...
def process_frame_simple(frame): ...
def write_frame(process2, frame) -> None: ...
def run(in_filename, out_filename, process_frame) -> None: ...

class DeepDream:
    t_obj: Incomplete
    def __init__(self) -> None: ...
    def T(self, layer_name): ...
    def process_frame(self, frame, iter_n: int = ..., step: float = ..., octave_n: int = ..., octave_scale: float = ...): ...
