from pathlib import Path
from dataclasses import dataclass

from .jobs import JobSizing as JobSizing

_RESERVED_CORES: int
CAMERA_EXTRACTION_JOB_CORES: int
_PARALLEL_EXTRACTION_THRESHOLD: int
SPAWNED_CHILD_MEMORY_MB: int
_MEMORY_ESTIMATE_TOLERANCE: float
_POOL_MEMORY_RESERVATION_DIVISOR: int
_ARCHIVE_DIRECTORY_RATIO: float
_MEMORY_BUDGET_FRACTION: float
_MINIMUM_MEMORY_BUDGET_MB: int
_MEMORY_ROUNDING_QUANTUM_MB: int
_BYTES_PER_MEGABYTE: int

@dataclass(frozen=True, slots=True)
class ArchiveFootprint:
    message_count: int
    archive_bytes: int

def resolve_archive_footprint(archive_path: Path) -> ArchiveFootprint: ...
def resolve_job_workers(footprint: ArchiveFootprint) -> int: ...
def estimate_job_memory_mb(footprint: ArchiveFootprint, cores: int) -> int: ...
def size_archive_job(archive_path: Path) -> JobSizing: ...
def resolve_core_budget(requested_budget: int) -> int: ...
def resolve_memory_budget_mb(requested_budget_mb: int) -> int: ...
def resolve_pool_size(job_count: int, core_budget: int, memory_budget_mb: int) -> int: ...
def resolve_host_memory_mb() -> int: ...
def _bytes_to_megabytes(byte_count: float) -> int: ...
def _apply_tolerance(memory_mb: int) -> int: ...
