from pathlib import Path
from threading import Lock, Event, Thread, Barrier
from dataclasses import field, dataclass
from collections.abc import Sequence
from concurrent.futures import Future, ProcessPoolExecutor
from multiprocessing.context import SpawnContext

from .jobs import (
    JobSizing as JobSizing,
    JobDescriptor as JobDescriptor,
)
from .worker import run_extraction_job as run_extraction_job
from .allocation import (
    SPAWNED_CHILD_MEMORY_MB as SPAWNED_CHILD_MEMORY_MB,
    resolve_host_memory_mb as resolve_host_memory_mb,
)

_MULTIPROCESSING_CONTEXT: SpawnContext
_POOL_WORKER_THREAD_CEILING: int
_POOL_WARMUP_TIMEOUT_SECONDS: float
_DISPATCH_POLL_SECONDS: float
_SESSION_FINISH_TIMEOUT_SECONDS: float
_MAXIMUM_POOL_REBUILDS: int
_MAXIMUM_JOB_REQUEUES: int
_EXECUTION_LOCK: Lock

@dataclass(slots=True)
class ActiveJob:
    job: JobDescriptor
    sizing: JobSizing
    future: Future[None]

@dataclass(slots=True)
class JobExecutionState:
    all_jobs: dict[tuple[str, str], JobDescriptor] = field(default_factory=dict)
    pending_jobs: list[tuple[JobDescriptor, JobSizing]] = field(default_factory=list)
    active_jobs: dict[tuple[str, str], ActiveJob] = field(default_factory=dict)
    core_budget: int = ...
    memory_budget_mb: int = ...
    pool_size: int = ...
    lock: Lock = field(default_factory=Lock)
    wakeup: Event = field(default_factory=Event)
    manager_thread: Thread | None = ...
    canceled: bool = ...
    finished_jobs: set[tuple[str, str]] = field(default_factory=set)
    pool_broken: bool = ...
    broken_jobs: list[tuple[JobDescriptor, JobSizing]] = field(default_factory=list)
    pool_rebuilds: int = ...
    requeue_counts: dict[tuple[str, str], int] = field(default_factory=dict)

_execution_state: JobExecutionState | None

def get_execution_state() -> JobExecutionState | None: ...
def start_execution_session(state: JobExecutionState) -> bool: ...
def session_is_active(state: JobExecutionState | None) -> bool: ...
def finish_execution_session(state: JobExecutionState) -> bool: ...
def group_jobs_by_tracker(state: JobExecutionState) -> dict[Path, list[JobDescriptor]]: ...
def _job_execution_manager(state: JobExecutionState) -> None: ...
def _select_admissible_jobs(
    pending: Sequence[tuple[JobDescriptor, JobSizing]],
    core_budget: int,
    memory_budget_mb: int,
    used_cores: int,
    used_memory_mb: int,
) -> tuple[list[tuple[JobDescriptor, JobSizing]], list[tuple[JobDescriptor, JobSizing]]]: ...
def _create_job_pool(pool_size: int) -> ProcessPoolExecutor: ...
def _pin_pool_worker(thread_count: int, barrier: Barrier) -> None: ...
def _warm_pool_worker() -> None: ...
def _reap_finished_jobs(state: JobExecutionState) -> None: ...
def _admit_pending_jobs(state: JobExecutionState, executor: ProcessPoolExecutor) -> None: ...
def _handle_broken_pool(state: JobExecutionState, executor: ProcessPoolExecutor) -> ProcessPoolExecutor | None: ...
def _abandon_batch(
    state: JobExecutionState, reason: str, orphaned: Sequence[tuple[JobDescriptor, JobSizing]] = ()
) -> None: ...
def _job_is_unrecorded(job: JobDescriptor) -> bool: ...
def _reconcile_unrecorded_job(job: JobDescriptor) -> None: ...
def _reset_job(job: JobDescriptor) -> None: ...
def _fail_job(job: JobDescriptor, error_message: str) -> None: ...
