from typing import Any
from pathlib import Path

from ..video import (
    TRACKER_FILENAME as TRACKER_FILENAME,
    LOG_ARCHIVE_SUFFIX as LOG_ARCHIVE_SUFFIX,
    TIMESTAMP_JOB_NAME as TIMESTAMP_JOB_NAME,
    CAMERA_TIMESTAMPS_DIRECTORY as CAMERA_TIMESTAMPS_DIRECTORY,
    generate_job_ids as generate_job_ids,
)
from .mcp_instance import mcp as mcp
from .mcp_execution import (
    PendingJob as PendingJob,
    JobExecutionState as JobExecutionState,
    get_execution_state as get_execution_state,
    set_execution_state as set_execution_state,
    job_execution_manager as job_execution_manager,
)

_RESERVED_CORES: int

def prepare_log_processing_batch_tool(
    log_directories: list[str], source_ids: list[str], output_directories: list[str]
) -> dict[str, Any]: ...
def execute_log_processing_jobs_tool(jobs: list[dict[str, str]], *, worker_budget: int = -1) -> dict[str, Any]: ...
def get_log_processing_status_tool() -> dict[str, Any]: ...
def get_log_processing_timing_tool() -> dict[str, Any]: ...
def cancel_log_processing_tool() -> dict[str, Any]: ...
def reset_log_processing_jobs_tool(tracker_path: str, source_ids: list[str] | None = None) -> dict[str, Any]: ...
def get_batch_status_overview_tool(root_directory: str) -> dict[str, Any]: ...
def analyze_camera_frame_statistics_tool(
    feather_files: list[str], drop_threshold_us: int = 0, max_drop_locations: int = 50
) -> dict[str, Any]: ...
def clean_log_processing_output_tool(output_directories: list[str]) -> dict[str, Any]: ...
def _read_tracker_status(tracker_path: Path) -> dict[str, Any]: ...
def _derive_tracker_status(summary: dict[str, Any]) -> str: ...
def _group_jobs_by_tracker(state: JobExecutionState) -> dict[Path, list[PendingJob]]: ...
def _analyze_single_feather(feather_file: str, drop_threshold_us: int, max_drop_locations: int) -> dict[str, Any]: ...
def _clean_single_output(output_directory: str) -> dict[str, Any]: ...
def _probe_archive_message_count(job: PendingJob) -> int: ...
