from typing import Any
from dataclasses import dataclass
from collections.abc import Iterable, Sequence

_DEFAULT_ITEM_LIMIT: int
_DEFAULT_DETAILED_LIMIT: int

@dataclass(frozen=True, slots=True)
class PageWindow:
    start: int
    length: int | None
    next_start_row: int | None
    @property
    def stop(self) -> int | None: ...

def resolve_page(total: int, limit: int, start_row: int) -> PageWindow: ...
def page_fields(window: PageWindow, total: int, listed: int) -> dict[str, Any]: ...
def resolve_detail_limit(limit: int | None, *, detailed: bool) -> int: ...
def item_breakdown(items: Sequence[dict[str, Any]], axes: tuple[str, ...]) -> dict[str, dict[str, int]]: ...
def project_item(item: dict[str, Any], fields: Sequence[str]) -> dict[str, Any]: ...
def reject_unknown(
    items: Sequence[dict[str, Any]], key: str, values: list[str], subject: str
) -> dict[str, Any] | None: ...
def _count_values(values: Iterable[Any]) -> dict[str, int]: ...
